# fly.toml app configuration file generated for projectip on 2025-03-27T23:18:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'projectip'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  SECRET_KEY = 'IXsZTf8_FH5xspvaeGiIj1aJTANKHbC9m6xBSuuRBcd6UXSfZeekqg97F03rywZ_Vwo'
  DEBUG = 'False'
  IPINFO_API_KEY = '3b5c89838fc09c'
  ALLOWED_HOSTS = '.fly.dev,localhost,127.0.0.1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
